name: Build and Publish VSA-Backend-2.1

on:
  [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
      
    - name: Setup-msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Restore NuGet packages
      run: nuget restore VaaApi/VaaApi.sln
    
    - name: Build Solution
      run: msbuild VaaApi/VaaApi.sln

    #- name: Azure Webapp Deploy
    #  uses: azure/webapps-deploy@v2
    #  with: 
    #    app-name: VaaApi
    #    publish-profile: ${{ secrets.azureWebAppPublishProfile }}
  
    - name: Deploy to Web Hosting
      uses: SamKirkland/FTP-Deploy-Action@master
      with:
        ftp-server: virtual-advisor.com
        ftp-username: ${{ secrets.ftp_username }}
        ftp-password: ${{ secrets.ftp_password }}

    - name: Upload Package
      uses: actions/upload-artifact@v1
      with:
        name: BuildArtifacts
        path: vaaapi #Deploy IIS Path
